name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Set this to the desired Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web app
      run: flutter build web --release --base-href "/flutter-word-game/"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web

  windows-build:
    runs-on: windows-latest
    
    steps:    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Set this to the desired Flutter version

    - name: Install dependencies
      run: flutter pub get
      working-directory: ${{ github.workspace }}

    - name: Build Windows binary
      run: flutter build windows --release
      working-directory: ${{ github.workspace }}

    - name: Compress build output
      run: Compress-Archive -Path $env:GITHUB_WORKSPACE\build\windows\runner\Release\* -DestinationPath $env:RUNNER_TEMP\build.zip
      shell: powershell
      env:
        RUNNER_TEMP: ${{ runner.temp }}
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Publish binaries
      run: gh release upload '1.0.12' "${{ env.RUNNER_TEMP }}\\build.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUNNER_TEMP: ${{ runner.temp }}

