name: Build and Deploy Flutter App

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Set this to the desired Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web app
      run: flutter build web --release --base-href "/flutter-word-game/"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web

    - name: Build Android APK
      run: flutter build apk --release

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  windows-build:
    runs-on: windows-latest

    steps:    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Set this to the desired Flutter version

    - name: Install dependencies
      run: flutter pub get
      working-directory: ${{ github.workspace }}

    - name: Build Windows binary
      run: flutter build windows --release
      working-directory: ${{ github.workspace }}

    - name: Compress build output
      run: |
        powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\build\windows\x64\runner\Release\* -DestinationPath $env:RUNNER_TEMP\windows-build.zip
      env:
        RUNNER_TEMP: ${{ runner.temp }}
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: ${{ runner.temp }}\windows-build.zip

  attach-release:
    runs-on: ubuntu-latest
    needs: [windows-build, android-build]

    steps:
    - name: Download Windows build artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-binary
        path: ./release/windows

    - name: Download Android APK artifact
      uses: actions/download-artifact@v4
      with:
        name: android-apk
        path: ./release/android

    - name: Get the latest release
      id: get_release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: latestRelease } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          return latestRelease.upload_url;


    - name: Upload Windows artifact to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./release/windows/windows-build.zip
        asset_name: windows-build.zip
        asset_content_type: application/zip

    - name: Upload Android APK to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./release/android/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive